### ISSUE TITLE
Ресёрч проблемы с производительностью js воркера

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/hawk.workers#155]

**Comment by kabachook** [comment]
- блочится event loop (видимо из-за парсинга соурсмепов)
- самая горячая функа это парсинг соурсмепов
- запросы в монгу тоже занимают какое-то время, но меньшее чем всё остальное

Профилирование по event loop + flamechart:
[prof.zip](https://github.com/codex-team/hawk.workers/files/5291767/prof.zip)
