### ISSUE TITLE
Handle broken tasks

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.workers#17]
What happened when we have an Exception in worker? For example, in JSON parsing.

Possible, tasks will stacked in `Registry->Worker` direction.

We need to provide scheme for handling this situation. For example, move this task to special queue `stash@errors/nodejs` and provide worker who will handle these tasks: 

- Log
- Notify us about broken task
- Allow to fix a problem and move task back to normal queue

Most important thing is not to lose user data, including broken. Also, exception can be throws due to our side bug in worker logic — so we should fix it and re-handle task.

**Comment by neSpecc** [comment]
It should be part of base library — maybe this is a reason to create own Registry wrapper or maybe it can be handled by the Base Worker.

**Comment by kabachook** [comment]
I suppose we can define dead-letter exchange, which if message rejected (or nack with requeue=false) will put it in stash queues https://www.rabbitmq.com/dlx.html
