### ISSUE TITLE
Error grouping worker

### ISSUE THREAD

**Issue by kabachook** [codex-team/hawk.workers#35]
New scheme:

```
Registry 
↓
<event>
↓
Worker by eventType
↓
<unified format event>
↓
Grouping worker
↓
Database (event:projectId or repetitions:projectId )
```

Grouping working behavior:
1. hash required fields, which are not dependent of time and random (`title`, `catherType`, `backtrace.file`)
2. check `events:<project._id>` collection for documents with `groupHash` field equals to computed hash
3. Write to database
    1. if document exists, update `count` +1, timestamp, and write **diff** of all fields to `repetitions:<project._id>` collection
    2. else create document with `count: 1` and write **all** fields to `events:<project._id>`

*events:<project._id>*
```jsonc
{
  // ... all event fields
  "groupHash": "acacdeadcafe11231", // Binary format
  "count": 5,
  "timestamp": 105131231
}
```

*repetitions:<project._id>*
```jsonc
{
  "groupHash": "acacdeadcafe11231", // Binary format
  // fields diff
}
```

**Comment by neSpecc** [comment]
Additional task: how to count event by days? 

One event can be occurred many times every day. It would be nice to group such occurrences by days, like in messengers. 

![](https://capella.pics/2ba3d053-9a3d-48f2-808b-ad8c091f13bc.jpg)

**Comment by nikmel2803** [comment]
already implemented
